@startuml
start
:Начало обработки;
if (Получена новая заявка?) then (Да)
  :Менеджер сверяет товар и чек;
  if (Соответствует ли случай\nправилам возврата?) then (Да)
    :Статус: Одобрено;
    :Возврат денег клиенту;
  else (Нет)
    :Статус: Отклонено;
    :Отправка причины отказа\n(обратной связи);
  endif
  :Конец процесса;
else (Нет)
  :Ожидание новых заявок;
  stop
endif
@enduml
