@startuml
start
:Клиент заходит в систему;
:Создать заявку на возврат товара;
:Заполнить данные;
if (Прикрепить вложения?) then (да)
  :Прикрепляет фото и чек;
else (нет)
  :Пропустить прикрепление;
endif
:Отправка заявки менеджеру;
:Статус: на рассмотрении;
stop
@enduml
